CREATE TABLE USER(
    UID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME CHAR(20) NOT NULL,
    PASSWORD CHAR(20) ,
    CHINAME CHAR(20),
    LOCID INTEGER,
    IMAGESAMPLE CHAR(100),
    AUDIOENGINE CHAR(100),
    CREATETIME DATETIME
    );
ALTER TABLE USER ADD unique(USERNAME);
ALTER TABLE USER MODIFY CHINAME CHAR(20) CHARACTER SET GBK;

CREATE TABLE AUDIO(
	OWNER BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(OWNER) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,
	AUDIOHASH CHAR(100) PRIMARY KEY,
	CREATETIME DATETIME
);

CREATE TABLE LOCATION(
    LOCID INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LOCATIONNAME CHAR(100),
    LONGITUDE DOUBLE,
    LATITUDE DOUBLE
);
INSERT INTO LOCATION VALUES(1,'SJTU',121.43574714660645,31.024988336871534);

CREATE TABLE DETECT(
    OWNER BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(OWNER) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,
    SESSIONID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AUDIOHASH CHAR(100),
    AUDIODETECT TINYINT,
    LONGITUDE FLOAT,
    LATITUDE FLOAT,
    FACEHASH CHAR(100),
    FACEDETECT FLOAT,
    DETECTTIME DATETIME
);
