CREATE TABLE USER(
    UID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME CHAR(20) ,
    PASSWORD CHAR(20) ,
    CHINAME CHAR(20),
    LOCID INTEGER,
    IMAGESAMPLE CHAR(100),
    AUDIOENGINE CHAR(100),
    CREATETIME DATETIME,
    DEPARTMENT CHAR(100),
    );
ALTER TABLE USER ADD UNIQUE(USERNAME);
ALTER TABLE USER MODIFY CHINAME CHAR(20) CHARACTER SET GBK;
ALTER TABLE USER MODIFY DEPARTMENT CHAR(20) CHARACTER SET GBK;

CREATE TABLE ADMINISTRATOR(
    UID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME CHAR(20),
    CHINAME CHAR(20),
    PASSWORD CHAR(20)
);
ALTER TABLE ADMINISTRATOR ADD UNIQUE(USERNAME);
ALTER TABLE ADMINISTRATOR MODIFY CHINAME CHAR(20) CHARACTER SET GBK;
INSERT INTO ADMINISTRATOR(USERNAME,PASSWORD) VALUES('admin','admin');

CREATE TABLE AUDIO(
	OWNER BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(OWNER) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,
	AUDIOHASH CHAR(100) PRIMARY KEY,
	CREATETIME DATETIME
);

CREATE TABLE LOCATION(
    LOCID INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LOCATIONNAME CHAR(100),
    LONGITUDE DOUBLE,
    LATITUDE DOUBLE,
    STARTTIME DATETIME,
    TERMITIME DATETIME
);
ALTER TABLE USER MODIFY LOCATIONNAME CHAR(100) CHARACTER SET GBK;
INSERT INTO LOCATION VALUES(1,'SJTU',121.43574714660645,31.024988336871534);

CREATE TABLE DETECT(
    OWNER BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(OWNER) REFERENCES USER(UID) ON DELETE CASCADE ON UPDATE CASCADE,
    SESSIONID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AUDIOHASH CHAR(100),
    AUDIODETECT TINYINT,
    LONGITUDE DOUBLE,
    LATITUDE DOUBLE,
    FACEHASH CHAR(100),
    FACEDETECT FLOAT,
    DETECTTIME DATETIME,
    STATUS BOOL
);

INSERT INTO USER(UID,USERNAME,CHINAME) VALUES (5100309145,'WELL147852','袁璠');
INSERT INTO USER(UID,USERNAME,CHINAME) VALUES (5101109071,'ronnie_alonso','李征');
INSERT INTO USER(UID,USERNAME,CHINAME) VALUES (5100209333,'oo7y','程尚义');
INSERT INTO USER(UID,USERNAME,CHINAME) VALUES (5100209356,'poisonxiu517','赵燎原');
INSERT INTO USER(UID,USERNAME,CHINAME) VALUES (5100309582,'chenguanghai123','陈光海');
